expected = {
    "sex": "牡",
    "name": "競走馬名",
    "birthday": "1991-02-08",
    "color": "栗毛",
    "trainer_id": "00000",
    "owner": "山田 太郎",
    "producer": "ノーザンファーム",
    "birthplace": "京都",
    "sire": "父",
    "mare": "母",
    "sire_sire": "父父",
    "sire_mare": "父母",
    "mare_sire": "母父",
    "mare_mare": "母母",
    "sire_sire_sire": "父父父",
    "sire_sire_mare": "父父母",
    "sire_mare_sire": "父母父",
    "mare_sire_sire": "母父父",
    "sire_mare_mare": "父母母",
    "mare_sire_mare": "母父母",
    "mare_mare_sire": "母母父",
    "mare_mare_mare": "母母母"
}
